<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EFCore.NamingConventions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="StackExchange.Redis" Version="3.3.1" />
    <PackageReference Include="Stripe.net" Version="52.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlashTix.Application\FlashTix.Application.csproj" />
  </ItemGroup>

</Project>
